name: GitHub Action Test

on:
  push:
    branches:
      - test
    paths:
      - back-end/**
      - .github/workflows/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Echo
        run: echo hello
